In [ ]:
import pandas as pd
import numpy as np

In [ ]:
df = pd.read_csv("/content/furniture_10k_FINAL (new).csv", sep=';')

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 17 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   year            10000 non-null  int64
 1   month           10000 non-null  int64
 2   day             10000 non-null  int64
 3   sales_date_std  10000 non-null  object
 4   order_id        10000 non-null  object
 5   customer_name   10000 non-null  object
 6   product_name    10000 non-null  object
 7   category        10000 non-null  object
 8   price           10000 non-null  int64
 9   quantity        10000 non-null  int64
 10  discount        10000 non-null  object
 11  total           10000 non-null  int64
 12  shipping_fee    10000 non-null  int64
 13  total_sales     10000 non-null  int64
 14  status          10000 non-null  object
 15  Kelurahan       10000 non-null  object
 16  Kota            10000 non-null  object
dtypes: int64(8), object(9)
memory usage: 1.3+ MB

In [ ]:
df

,year,month,day,sales_date_std,order_id,customer_name,product_name,category,price,quantity,discount,total,shipping_fee,total_sales,status,Kelurahan,Kota
0,2025,7,31,31/07/2025,ORD00001,Customer_332,Kitchen Set,Dapur,9500000,1,0,9500000,60000,9560000,cancelled,Kelurahan 120,Jakarta Pusat
1,2025,11,3,03/11/2025,ORD00002,Customer_1150,Nakas,Kamar Tidur,1000000,2,0,2000000,60000,2060000,completed,Kelurahan 9,Jakarta Pusat
2,2025,10,31,31/10/2025,ORD00003,Customer_2122,Kursi Bar,Ruang Makan,1295000,2,0,2590000,60000,2650000,completed,Kelurahan 108,Jakarta Pusat
3,2025,6,19,19/06/2025,ORD00004,Customer_2636,Kasur,Kamar Tidur,5500000,3,0,16500000,50000,16550000,completed,Kelurahan 36,Bogor
4,2025,6,19,19/06/2025,ORD00005,Customer_3379,Meja Makan,Ruang Makan,3200000,3,0,9600000,60000,9660000,completed,Kelurahan 73,Tangerang
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,2025,5,23,23/05/2025,ORD09996,Customer_1067,Rak Buku,Penyimpanan,1100000,2,0,2200000,60000,2260000,cancelled,Kelurahan 3,Tangerang Selatan
9996,2025,11,18,18/11/2025,ORD09997,Customer_2082,Lemari Dapur,Dapur,1850000,3,0,5550000,60000,5610000,completed,Kelurahan 196,Jakarta Utara
9997,2025,4,4,04/04/2025,ORD09998,Customer_2474,Rak Sepatu,Penyimpanan,650000,2,"0,1",1170000,60000,1230000,completed,Kelurahan 56,Tangerang Selatan
9998,2025,6,26,26/06/2025,ORD09999,Customer_986,Meja Rias,Kamar Tidur,1750000,3,0,5250000,60000,5310000,completed,Kelurahan 75,Jakarta Barat
9999,2025,4,11,11/04/2025,ORD10000,Customer_202,Rak Sepatu,Penyimpanan,650000,3,0,1950000,50000,2000000,cancelled,Kelurahan 178,Bekasi

In [ ]:
df['sales_date_std'] = pd.to_datetime(df['sales_date_std'])

/tmp/ipykernel_3371/723480819.py:1: UserWarning: Parsing dates in %d/%m/%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  df['sales_date_std'] = pd.to_datetime(df['sales_date_std'])

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 17 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   year            10000 non-null  int64
 1   month           10000 non-null  int64
 2   day             10000 non-null  int64
 3   sales_date_std  10000 non-null  datetime64[ns]
 4   order_id        10000 non-null  object
 5   customer_name   10000 non-null  object
 6   product_name    10000 non-null  object
 7   category        10000 non-null  object
 8   price           10000 non-null  int64
 9   quantity        10000 non-null  int64
 10  discount        10000 non-null  object
 11  total           10000 non-null  int64
 12  shipping_fee    10000 non-null  int64
 13  total_sales     10000 non-null  int64
 14  status          10000 non-null  object
 15  Kelurahan       10000 non-null  object
 16  Kota            10000 non-null  object
dtypes: datetime64[ns](1), int64(8), object(8)
memory usage: 1.3+ MB

In [ ]:
df.isnull().sum()

year              0
month             0
day               0
sales_date_std    0
order_id          0
customer_name     0
product_name      0
category          0
price             0
quantity          0
discount          0
total             0
shipping_fee      0
total_sales       0
status            0
Kelurahan         0
Kota              0
dtype: int64

In [ ]:
df.duplicated().sum()

np.int64(0)

In [ ]:
bins = [0, 500000, 2000000, float ('inf')]
labels = ['Low', 'Mid', 'High']

df['revenue_tier'] = pd.cut(df['total_sales'], bins=bins, labels=labels)

In [ ]:
df

,year,month,day,sales_date_std,order_id,customer_name,product_name,category,price,quantity,discount,total,shipping_fee,total_sales,status,Kelurahan,Kota,revenue_tier
0,2025,7,31,2025-07-31,ORD00001,Customer_332,Kitchen Set,Dapur,9500000,1,0,9500000,60000,9560000,cancelled,Kelurahan 120,Jakarta Pusat,High
1,2025,11,3,2025-11-03,ORD00002,Customer_1150,Nakas,Kamar Tidur,1000000,2,0,2000000,60000,2060000,completed,Kelurahan 9,Jakarta Pusat,High
2,2025,10,31,2025-10-31,ORD00003,Customer_2122,Kursi Bar,Ruang Makan,1295000,2,0,2590000,60000,2650000,completed,Kelurahan 108,Jakarta Pusat,High
3,2025,6,19,2025-06-19,ORD00004,Customer_2636,Kasur,Kamar Tidur,5500000,3,0,16500000,50000,16550000,completed,Kelurahan 36,Bogor,High
4,2025,6,19,2025-06-19,ORD00005,Customer_3379,Meja Makan,Ruang Makan,3200000,3,0,9600000,60000,9660000,completed,Kelurahan 73,Tangerang,High
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,2025,5,23,2025-05-23,ORD09996,Customer_1067,Rak Buku,Penyimpanan,1100000,2,0,2200000,60000,2260000,cancelled,Kelurahan 3,Tangerang Selatan,High
9996,2025,11,18,2025-11-18,ORD09997,Customer_2082,Lemari Dapur,Dapur,1850000,3,0,5550000,60000,5610000,completed,Kelurahan 196,Jakarta Utara,High
9997,2025,4,4,2025-04-04,ORD09998,Customer_2474,Rak Sepatu,Penyimpanan,650000,2,"0,1",1170000,60000,1230000,completed,Kelurahan 56,Tangerang Selatan,Mid
9998,2025,6,26,2025-06-26,ORD09999,Customer_986,Meja Rias,Kamar Tidur,1750000,3,0,5250000,60000,5310000,completed,Kelurahan 75,Jakarta Barat,High
9999,2025,4,11,2025-04-11,ORD10000,Customer_202,Rak Sepatu,Penyimpanan,650000,3,0,1950000,50000,2000000,cancelled,Kelurahan 178,Bekasi,Mid

In [ ]:
import pandas as pd

result = df.groupby(['Kota', 'category'])[
    ['total_sales', 'quantity']
].mean()

print(result)

                                total_sales  quantity
Kota              category
Bekasi            Dapur        1.046391e+07  1.896552
                  Kamar Tidur  6.016584e+06  2.049822
                  Penyimpanan  1.734891e+06  1.891304
                  Ruang Kerja  2.020631e+06  1.932039
                  Ruang Makan  3.599719e+06  2.000000
                  Ruang Tamu   5.717222e+06  1.897119
Bogor             Dapur        1.068305e+07  2.045977
                  Kamar Tidur  6.104723e+06  1.986971
                  Penyimpanan  1.826923e+06  2.048077
                  Ruang Kerja  2.125000e+06  2.031496
                  Ruang Makan  3.588694e+06  2.032895
                  Ruang Tamu   5.784422e+06  2.019920
Depok             Dapur        9.769444e+06  1.873016
                  Kamar Tidur  6.097664e+06  2.012461
                  Penyimpanan  1.845172e+06  1.982759
                  Ruang Kerja  2.043421e+06  1.921053
                  Ruang Makan  3.345410e+06  2.089552
                  Ruang Tamu   5.899378e+06  2.000000
Jakarta Barat     Dapur        1.174734e+07  2.010638
                  Kamar Tidur  6.628050e+06  2.075472
                  Penyimpanan  1.732475e+06  1.878788
                  Ruang Kerja  2.033958e+06  1.958333
                  Ruang Makan  3.663292e+06  2.041667
                  Ruang Tamu   5.855283e+06  2.039130
Jakarta Pusat     Dapur        1.058330e+07  1.855670
                  Kamar Tidur  6.461751e+06  2.068249
                  Penyimpanan  1.931481e+06  2.101852
                  Ruang Kerja  2.052647e+06  1.892157
                  Ruang Makan  3.118588e+06  1.941176
                  Ruang Tamu   6.191224e+06  2.069388
Jakarta Selatan   Dapur        1.118000e+07  1.978947
                  Kamar Tidur  6.476564e+06  2.039877
                  Penyimpanan  1.822556e+06  1.966667
                  Ruang Kerja  1.909771e+06  1.917431
                  Ruang Makan  3.277242e+06  1.932515
                  Ruang Tamu   5.734896e+06  1.920833
Jakarta Timur     Dapur        1.096802e+07  1.990099
                  Kamar Tidur  5.960086e+06  1.958904
                  Penyimpanan  1.807456e+06  2.008772
                  Ruang Kerja  2.078684e+06  1.936842
                  Ruang Makan  3.348185e+06  2.034247
                  Ruang Tamu   5.618623e+06  1.975709
Jakarta Utara     Dapur        1.230638e+07  2.062500
                  Kamar Tidur  6.220743e+06  2.046647
                  Penyimpanan  1.903434e+06  2.080808
                  Ruang Kerja  2.190556e+06  2.166667
                  Ruang Makan  3.728662e+06  1.952703
                  Ruang Tamu   5.817957e+06  2.104348
Tangerang         Dapur        1.031302e+07  1.912088
                  Kamar Tidur  5.919894e+06  1.890459
                  Penyimpanan  1.750872e+06  2.000000
                  Ruang Kerja  1.834528e+06  1.849057
                  Ruang Makan  3.729512e+06  1.988304
                  Ruang Tamu   5.722078e+06  1.995671
Tangerang Selatan Dapur        8.421337e+06  1.861386
                  Kamar Tidur  6.383163e+06  1.948882
                  Penyimpanan  1.788146e+06  2.022472
                  Ruang Kerja  2.081802e+06  1.918605
                  Ruang Makan  3.772370e+06  2.070423
                  Ruang Tamu   5.835717e+06  2.008696

In [ ]:
sales_category = df.groupby('category')['total_sales'].sum().reset_index()

sales_category = sales_category.sort_values(
    by='total_sales',
    ascending=False
)

print(sales_category)

      category  total_sales
1  Kamar Tidur  19466170000
5   Ruang Tamu  13845615000
0        Dapur  10538790000
4  Ruang Makan   5352993500
3  Ruang Kerja   2014215000
2  Penyimpanan   1812005000

In [ ]:
city_quantity = df.groupby('Kota')['quantity'].sum().reset_index()

city_quantity = city_quantity.sort_values(
    by='quantity',
    ascending=False
)

print(city_quantity)

                 Kota  quantity
7       Jakarta Utara      2107
4       Jakarta Pusat      2101
1               Bogor      2075
3       Jakarta Barat      2035
5     Jakarta Selatan      2015
2               Depok      2004
6       Jakarta Timur      1971
9   Tangerang Selatan      1899
8           Tangerang      1878
0              Bekasi      1863

In [ ]:
avg_sales = df.groupby('category')['total_sales'].mean().reset_index()

avg_sales = avg_sales.sort_values(
    by='total_sales',
    ascending=False
)

print(avg_sales)

      category   total_sales
0        Dapur  1.063450e+07
1  Kamar Tidur  6.237158e+06
5   Ruang Tamu  5.817485e+06
4  Ruang Makan  3.519391e+06
3  Ruang Kerja  2.034561e+06
2  Penyimpanan  1.817457e+06